[[redirects]]
  from = "/if-i-have-flat-feet-should-i-wear-insoles/"
  to = "/blog/if-i-have-flat-feet-should-i-wear-insoles/"
  status = 301
  force = true
 [[redirects]]
  from = "/how-much-does-an-ankle-replacement-cost/"
  to = "/blog/how-much-does-an-ankle-replacement-cost/"
  status = 301
  force = true
 [[redirects]]
  from = "/what-are-the-risks-with-an-ankle-replacement/"
  to = "/blog/what-are-the-risks-with-an-ankle-replacement/"
  status = 301
  force = true
 [[redirects]]
  from = "/ankle-replacement-pictures/"
  to = "/blog/ankle-replacement-pictures/"
  status = 301
  force = true
 [[redirects]]
  from = "/best-foot-and-ankle-surgeon-in-london/"
  to = "/blog/best-foot-and-ankle-surgeon-in-london/"
  status = 301
  force = true
 [[redirects]]
  from = "/ankle-replacement-surgery/"
  to = "/blog/ankle-replacement-surgery/"
  status = 301
  force = true
 [[redirects]]
  from = "/high-ankle-sprain/"
  to = "/blog/high-ankle-sprain/"
  status = 301
  force = true
 [[redirects]]
  from = "/plantar-fasciitis-heel-pain/"
  to = "/blog/plantar-fasciitis-heel-pain/"
  status = 301
  force = true
 [[redirects]]
  from = "/clicking-joints/"
  to = "/blog/clicking-joints/"
  status = 301
  force = true
 [[redirects]]
  from = "/covid-19-coronavirus-pandemic/"
  to = "/blog/covid-19-coronavirus-pandemic/"
  status = 301
  force = true
 [[redirects]]
  from = "/who-is-the-best-ankle-surgeon-in-london/"
  to = "/blog/who-is-the-best-ankle-surgeon-in-london/"
  status = 301
  force = true
 [[redirects]]
  from = "/ankle-replacement-ankle-fusion/"
  to = "/blog/ankle-replacement-ankle-fusion/"
  status = 301
  force = true
 [[redirects]]
  from = "/sprained-ankle-treatment/"
  to = "/blog/sprained-ankle-treatment/"
  status = 301
  force = true
 [[redirects]]
  from = "/who-is-the-best-ankle-and-foot-surgeon-in-london/"
  to = "/blog/who-is-the-best-ankle-and-foot-surgeon-in-london/"
  status = 301
  force = true
 [[redirects]]
  from = "/break_and_a_fracture/"
  to = "/blog/break_and_a_fracture/"
  status = 301
  force = true
 [[redirects]]
  from = "/what-is-the-difference-between-osteoporosis-and-osteoarthritis/"
  to = "/blog/what-is-the-difference-between-osteoporosis-and-osteoarthritis/"
  status = 301
  force = true
 [[redirects]]
  from = "/why-does-my-big-toe-hurt/"
  to = "/blog/why-does-my-big-toe-hurt/"
  status = 301
  force = true
 [[redirects]]
  from = "/can-i-do-sports-after-an-ankle-replacement/"
  to = "/blog/can-i-do-sports-after-an-ankle-replacement/"
  status = 301
  force = true
 [[redirects]]
  from = "/hallux-rigidus-painful-big-toe/"
  to = "/blog/hallux-rigidus-painful-big-toe/"
  status = 301
  force = true
 [[redirects]]
  from = "/find-london-best-foot-and-ankle-surgeon/"
  to = "/blog/find-london-best-foot-and-ankle-surgeon/"
  status = 301
  force = true
 [[redirects]]
  from = "/find-best-uk-ankle-replacement-surgeon/"
  to = "/blog/find-best-uk-ankle-replacement-surgeon/"
  status = 301
  force = true
 [[redirects]]
  from = "/extracorporeal-shock-wave-therapy/"
  to = "/blog/extracorporeal-shock-wave-therapy/"
  status = 301
  force = true
 [[redirects]]
  from = "/achilles-tendinopathy/"
  to = "/blog/achilles-tendinopathy/"
  status = 301
  force = true
 [[redirects]]
  from = "/common-running-injuries/"
  to = "/blog/common-running-injuries/"
  status = 301
  force = true
 [[redirects]]
  from = "/ankle-fusion-surgery/"
  to = "/blog/ankle-fusion-surgery/"
  status = 301
  force = true
 [[redirects]]
  from = "/ankle-arthritis-osteoarthritis/"
  to = "/blog/ankle-arthritis-osteoarthritis/"
  status = 301
  force = true
 