// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from '@prismicio/client';

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

/**
 * Content for Author documents
 */
interface AuthorDocumentData {
  /**
   * Profile Image field in *Author*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: author.profile_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  profile_image: prismic.ImageField<never>;

  /**
   * Name field in *Author*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: author.name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField;

  /**
   * Email field in *Author*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: author.email
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  email: prismic.KeyTextField;

  /**
   * Description field in *Author*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: author.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Link field in *Author*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: author.link
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;
}

/**
 * Author document from Prismic
 *
 * - **API ID**: `author`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type AuthorDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<
  Simplify<AuthorDocumentData>,
  'author',
  Lang
>;

type ContactDocumentDataSlicesSlice = never;

/**
 * Content for Contact documents
 */
interface ContactDocumentData {
  /**
   * Heading field in *Contact*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.heading
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading: prismic.KeyTextField;

  /**
   * Subtitle field in *Contact*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.subtitle
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  subtitle: prismic.KeyTextField;

  /**
   * Lead field in *Contact*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.lead
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  lead: prismic.KeyTextField;

  /**
   * Email Address field in *Contact*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.email_address
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  email_address: prismic.KeyTextField;

  /**
   * Phone Number field in *Contact*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.phone_number
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  phone_number: prismic.KeyTextField;

  /**
   * Form Image field in *Contact*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.form_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  form_image: prismic.ImageField<never>;

  /**
   * Form Heading field in *Contact*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.form_heading
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  form_heading: prismic.KeyTextField;

  /**
   * Form Body field in *Contact*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.form_body
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  form_body: prismic.KeyTextField;

  /**
   * Slice Zone field in *Contact*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<ContactDocumentDataSlicesSlice> /**
   * Meta Title field in *Contact*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: contact.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Contact*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: contact.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Contact*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Contact document from Prismic
 *
 * - **API ID**: `contact`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ContactDocument<Lang extends string = string> = prismic.PrismicDocumentWithoutUID<
  Simplify<ContactDocumentData>,
  'contact',
  Lang
>;

type DownloadDocumentDataSlicesSlice = never;

/**
 * Content for Download documents
 */
interface DownloadDocumentData {
  /**
   * name field in *Download*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: download.name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField;

  /**
   * Feature Image field in *Download*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: download.feature_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  feature_image: prismic.ImageField<never>;

  /**
   * Featured field in *Download*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: download.featured
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  featured: prismic.BooleanField;

  /**
   * Publishing Date field in *Download*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: download.publishing_date
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#date
   */
  publishing_date: prismic.DateField;

  /**
   * Category field in *Download*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: download.category
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  category: prismic.ContentRelationshipField<'post_category'>;

  /**
   * Author field in *Download*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: download.author
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  author: prismic.ContentRelationshipField<'author'>;

  /**
   * Description field in *Download*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: download.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * File field in *Download*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: *None*
   * - **API ID Path**: download.file
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  file: prismic.LinkToMediaField;

  /**
   * Slice Zone field in *Download*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: download.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<DownloadDocumentDataSlicesSlice>;
}

/**
 * Download document from Prismic
 *
 * - **API ID**: `download`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type DownloadDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<
  Simplify<DownloadDocumentData>,
  'download',
  Lang
>;

/**
 * Content for FAQ documents
 */
interface FaqDocumentData {
  /**
   * Heading field in *FAQ*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faq.heading
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading: prismic.KeyTextField;

  /**
   * Body field in *FAQ*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faq.body
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  body: prismic.RichTextField;
}

/**
 * FAQ document from Prismic
 *
 * - **API ID**: `faq`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type FaqDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<
  Simplify<FaqDocumentData>,
  'faq',
  Lang
>;

type HomeDocumentDataSlicesSlice = HeroSlice | FaqsSlice | HeaderBlockSlice | CallToActionSlice;

/**
 * Content for Home documents
 */
interface HomeDocumentData {
  /**
   * Slice Zone field in *Home*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: home.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<HomeDocumentDataSlicesSlice> /**
   * Meta Title field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: home.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: home.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Home*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Home document from Prismic
 *
 * - **API ID**: `home`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomeDocument<Lang extends string = string> = prismic.PrismicDocumentWithoutUID<
  Simplify<HomeDocumentData>,
  'home',
  Lang
>;

type LegalDocumentDataSlicesSlice = never;

/**
 * Content for Legal documents
 */
interface LegalDocumentData {
  /**
   * Title field in *Legal*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: legal.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Last Update field in *Legal*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: legal.last_update
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#date
   */
  last_update: prismic.DateField;

  /**
   * Body field in *Legal*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: legal.body
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  body: prismic.RichTextField;

  /**
   * Slice Zone field in *Legal*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: legal.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<LegalDocumentDataSlicesSlice> /**
   * Meta Title field in *Legal*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: legal.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Legal*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: legal.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Legal*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: legal.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Legal document from Prismic
 *
 * - **API ID**: `legal`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type LegalDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<
  Simplify<LegalDocumentData>,
  'legal',
  Lang
>;

/**
 * Item in *Navigation Bar → Navigation Items*
 */
export interface NavigationBarDocumentDataNavigationItemsItem {
  /**
   * Navigation Item field in *Navigation Bar → Navigation Items*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation_bar.navigation_items[].navigation_item
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  navigation_item: prismic.ContentRelationshipField<'navigation_element'>;
}

/**
 * Content for Navigation Bar documents
 */
interface NavigationBarDocumentData {
  /**
   * Navigation Items field in *Navigation Bar*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation_bar.navigation_items[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  navigation_items: prismic.GroupField<Simplify<NavigationBarDocumentDataNavigationItemsItem>>;
}

/**
 * Navigation Bar document from Prismic
 *
 * - **API ID**: `navigation_bar`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type NavigationBarDocument<Lang extends string = string> = prismic.PrismicDocumentWithoutUID<
  Simplify<NavigationBarDocumentData>,
  'navigation_bar',
  Lang
>;

/**
 * Item in *Navigation Element → Subs*
 */
export interface NavigationElementDocumentDataSubsItem {
  /**
   * Icon field in *Navigation Element → Subs*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation_element.subs[].icon
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  icon: prismic.ImageField<never>;

  /**
   * Label field in *Navigation Element → Subs*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation_element.subs[].label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField;

  /**
   * Description field in *Navigation Element → Subs*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation_element.subs[].description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Link field in *Navigation Element → Subs*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation_element.subs[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;
}

/**
 * Item in *Navigation Element → CTA*
 */
export interface NavigationElementDocumentDataCtaItem {
  /**
   * Url field in *Navigation Element → CTA*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation_element.cta[].url
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  url: prismic.LinkField;

  /**
   * Text field in *Navigation Element → CTA*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation_element.cta[].text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  text: prismic.KeyTextField;

  /**
   * Icon field in *Navigation Element → CTA*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation_element.cta[].icon
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  icon: prismic.ImageField<never>;
}

/**
 * Content for Navigation Element documents
 */
interface NavigationElementDocumentData {
  /**
   * Label field in *Navigation Element*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation_element.label
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField;

  /**
   * Link field in *Navigation Element*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation_element.link
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;

  /**
   * Subs field in *Navigation Element*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation_element.subs[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  subs: prismic.GroupField<Simplify<NavigationElementDocumentDataSubsItem>>;

  /**
   * CTA field in *Navigation Element*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation_element.cta[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  cta: prismic.GroupField<Simplify<NavigationElementDocumentDataCtaItem>>;
}

/**
 * Navigation Element document from Prismic
 *
 * - **API ID**: `navigation_element`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type NavigationElementDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<
  Simplify<NavigationElementDocumentData>,
  'navigation_element',
  Lang
>;

type PageDocumentDataSlicesSlice =
  | SectionSlice
  | TestimonialSlice
  | CallToActionSlice
  | HeaderBlockSlice
  | HeroSlice
  | FaqsSlice;

/**
 * Content for Page documents
 */
interface PageDocumentData {
  /**
   * Title field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: page.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Parent field in *Page*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: page.parent
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  parent: prismic.LinkField;

  /**
   * Slice Zone field in *Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<PageDocumentDataSlicesSlice> /**
   * Meta Title field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<
  Simplify<PageDocumentData>,
  'page',
  Lang
>;

/**
 * Content for Post Category documents
 */
interface PostCategoryDocumentData {
  /**
   * Name field in *Post Category*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Category Name
   * - **API ID Path**: post_category.name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField;
}

/**
 * Post Category document from Prismic
 *
 * - **API ID**: `post_category`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PostCategoryDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<
  Simplify<PostCategoryDocumentData>,
  'post_category',
  Lang
>;

/**
 * Content for Post Tags documents
 */
interface PostTagsDocumentData {
  /**
   * Name field in *Post Tags*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: post_tags.name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField;
}

/**
 * Post Tags document from Prismic
 *
 * - **API ID**: `post_tags`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PostTagsDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<
  Simplify<PostTagsDocumentData>,
  'post_tags',
  Lang
>;

/**
 * Item in *Posts → Tags*
 */
export interface PostsDocumentDataTagsItem {
  /**
   * Tag field in *Posts → Tags*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: posts.tags[].tag
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  tag: prismic.ContentRelationshipField<'post_tags'>;
}

type PostsDocumentDataSlicesSlice = never;

/**
 * Content for Posts documents
 */
interface PostsDocumentData {
  /**
   * Feature Image field in *Posts*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: posts.feature_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  feature_image: prismic.ImageField<never>;

  /**
   * Featured field in *Posts*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: true
   * - **API ID Path**: posts.featured
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  featured: prismic.BooleanField;

  /**
   * Author field in *Posts*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: posts.author
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  author: prismic.ContentRelationshipField<'author'>;

  /**
   * Category field in *Posts*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: posts.category
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  category: prismic.ContentRelationshipField<'post_category'>;

  /**
   * Tags field in *Posts*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: posts.tags[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  tags: prismic.GroupField<Simplify<PostsDocumentDataTagsItem>>;

  /**
   * Publishing Date field in *Posts*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: posts.publishing_date
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#date
   */
  publishing_date: prismic.DateField;

  /**
   * Title field in *Posts*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Title
   * - **API ID Path**: posts.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Excerpt field in *Posts*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Excerpt
   * - **API ID Path**: posts.excerpt
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  excerpt: prismic.RichTextField;

  /**
   * Content field in *Posts*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Post body content
   * - **API ID Path**: posts.content
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField;

  /**
   * Slice Zone field in *Posts*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: posts.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<PostsDocumentDataSlicesSlice> /**
   * Meta title field in *Posts*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: posts.meta_title
   * - **Tab**: SEO & Meta Data
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Posts*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: posts.meta_description
   * - **Tab**: SEO & Meta Data
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Posts*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: posts.meta_image
   * - **Tab**: SEO & Meta Data
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Posts document from Prismic
 *
 * - **API ID**: `posts`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PostsDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<
  Simplify<PostsDocumentData>,
  'posts',
  Lang
>;

/**
 * Item in *Settings → Contact Form Enquiries*
 */
export interface SettingsDocumentDataContactFormEnquiriesItem {
  /**
   * Label field in *Settings → Contact Form Enquiries*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.contact_form_enquiries[].label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField;

  /**
   * Value field in *Settings → Contact Form Enquiries*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.contact_form_enquiries[].value
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  value: prismic.KeyTextField;
}

/**
 * Item in *Settings → Secondary Navigation*
 */
export interface SettingsDocumentDataSecondaryNavigationItem {
  /**
   * Label field in *Settings → Secondary Navigation*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.secondary_navigation[].label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField;

  /**
   * Link field in *Settings → Secondary Navigation*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.secondary_navigation[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;
}

/**
 * Item in *Settings → Social Media*
 */
export interface SettingsDocumentDataSocialMediaItem {
  /**
   * Type field in *Settings → Social Media*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.social_media[].type
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  type: prismic.SelectField<'facebook' | 'instagram' | 'twitter' | 'gitHub' | 'youtube' | 'tiktok' | 'linkedin'>;

  /**
   * Name field in *Settings → Social Media*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.social_media[].name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField;

  /**
   * Url field in *Settings → Social Media*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.social_media[].url
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  url: prismic.LinkField;
}

/**
 * Content for Settings documents
 */
interface SettingsDocumentData {
  /**
   * Copyright Line field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.copyright_line
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  copyright_line: prismic.KeyTextField;

  /**
   * Contact Form Enquiries field in *Settings*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.contact_form_enquiries[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  contact_form_enquiries: prismic.GroupField<Simplify<SettingsDocumentDataContactFormEnquiriesItem>>;

  /**
   * Secondary Navigation field in *Settings*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.secondary_navigation[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  secondary_navigation: prismic.GroupField<Simplify<SettingsDocumentDataSecondaryNavigationItem>>;

  /**
   * Social Media field in *Settings*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.social_media[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  social_media: prismic.GroupField<Simplify<SettingsDocumentDataSocialMediaItem>>;

  /**
   * Footer Cta Lable field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.footer_cta_lable
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  footer_cta_lable: prismic.KeyTextField;

  /**
   * Footer Cta Heading field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.footer_cta_heading
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  footer_cta_heading: prismic.KeyTextField;

  /**
   * Footer Cta Body field in *Settings*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.footer_cta_body
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  footer_cta_body: prismic.RichTextField;

  /**
   * Footer Cta Links field in *Settings*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.footer_cta_links
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  footer_cta_links: prismic.Repeatable<prismic.LinkField>;

  /**
   * Canonical Url field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.canonical_url
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  canonical_url: prismic.KeyTextField;

  /**
   * Share Image field in *Settings*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.share_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  share_image: prismic.ImageField<never>;

  /**
   * Meta title field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.meta_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.meta_description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Keywords field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.meta_keywords
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_keywords: prismic.KeyTextField;
}

/**
 * Settings document from Prismic
 *
 * - **API ID**: `settings`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SettingsDocument<Lang extends string = string> = prismic.PrismicDocumentWithoutUID<
  Simplify<SettingsDocumentData>,
  'settings',
  Lang
>;

type VideoDocumentDataSlicesSlice = never;

/**
 * Content for Video documents
 */
interface VideoDocumentData {
  /**
   * Name field in *Video*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: video.name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField;

  /**
   * Author field in *Video*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: video.author
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  author: prismic.ContentRelationshipField<'author'>;

  /**
   * Publishing Date field in *Video*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: video.publishing_date
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#date
   */
  publishing_date: prismic.DateField;

  /**
   * Featured field in *Video*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: video.featured
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  featured: prismic.BooleanField;

  /**
   * Poster field in *Video*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: video.poster
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  poster: prismic.ImageField<never>;

  /**
   * Category field in *Video*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: video.category
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  category: prismic.ContentRelationshipField<'post_category'>;

  /**
   * Description field in *Video*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: video.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Video Url field in *Video*
   *
   * - **Field Type**: Embed
   * - **Placeholder**: *None*
   * - **API ID Path**: video.video_url
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#embed
   */
  video_url: prismic.EmbedField;

  /**
   * Slice Zone field in *Video*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: video.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<VideoDocumentDataSlicesSlice> /**
   * Meta Title field in *Video*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: video.meta_title
   * - **Tab**: SEO & Meta Data
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Video*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: video.meta_description
   * - **Tab**: SEO & Meta Data
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Video*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: video.meta_image
   * - **Tab**: SEO & Meta Data
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Video document from Prismic
 *
 * - **API ID**: `video`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type VideoDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<
  Simplify<VideoDocumentData>,
  'video',
  Lang
>;

export type AllDocumentTypes =
  | AuthorDocument
  | ContactDocument
  | DownloadDocument
  | FaqDocument
  | HomeDocument
  | LegalDocument
  | NavigationBarDocument
  | NavigationElementDocument
  | PageDocument
  | PostCategoryDocument
  | PostTagsDocument
  | PostsDocument
  | SettingsDocument
  | VideoDocument;

/**
 * Primary content in *CallToAction → Default → Primary*
 */
export interface CallToActionSliceDefaultPrimary {
  /**
   * Heading field in *CallToAction → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: call_to_action.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading: prismic.KeyTextField;

  /**
   * Body field in *CallToAction → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: call_to_action.default.primary.body
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  body: prismic.RichTextField;

  /**
   * Links field in *CallToAction → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: call_to_action.default.primary.links
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  links: prismic.Repeatable<prismic.LinkField>;

  /**
   * Image field in *CallToAction → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: call_to_action.default.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Default variation for CallToAction Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CallToActionSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<CallToActionSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *CallToAction → Image → Primary*
 */
export interface CallToActionSliceImagePrimary {
  /**
   * Heading field in *CallToAction → Image → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: call_to_action.image.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading: prismic.KeyTextField;

  /**
   * Body field in *CallToAction → Image → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: call_to_action.image.primary.body
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  body: prismic.RichTextField;

  /**
   * Links field in *CallToAction → Image → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: call_to_action.image.primary.links
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  links: prismic.Repeatable<prismic.LinkField>;

  /**
   * Image field in *CallToAction → Image → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: call_to_action.image.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Image variation for CallToAction Slice
 *
 * - **API ID**: `image`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CallToActionSliceImage = prismic.SharedSliceVariation<
  'image',
  Simplify<CallToActionSliceImagePrimary>,
  never
>;

/**
 * Slice variation for *CallToAction*
 */
type CallToActionSliceVariation = CallToActionSliceDefault | CallToActionSliceImage;

/**
 * CallToAction Shared Slice
 *
 * - **API ID**: `call_to_action`
 * - **Description**: CallToAction
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CallToActionSlice = prismic.SharedSlice<'call_to_action', CallToActionSliceVariation>;

/**
 * Item in *Faqs → Default → Primary → FAQs*
 */
export interface FaqsSliceDefaultPrimaryFaqsItem {
  /**
   * FAQ field in *Faqs → Default → Primary → FAQs*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: faqs.default.primary.faqs[].faq
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  faq: prismic.ContentRelationshipField<'faq'>;
}

/**
 * Item in *Faqs → Grid → Primary → FAQs*
 */
export interface FaqsSliceGridPrimaryFaqsItem {
  /**
   * FAQ field in *Faqs → Grid → Primary → FAQs*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: faqs.grid.primary.faqs[].faq
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  faq: prismic.ContentRelationshipField<'faq'>;
}

/**
 * Item in *Faqs → Column → Primary → FAQs*
 */
export interface FaqsSliceColumnPrimaryFaqsItem {
  /**
   * FAQ field in *Faqs → Column → Primary → FAQs*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: faqs.column.primary.faqs[].faq
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  faq: prismic.ContentRelationshipField<'faq'>;
}

/**
 * Item in *Faqs → Column Collapsible  → Primary → FAQs*
 */
export interface FaqsSliceColumnCollapsiblePrimaryFaqsItem {
  /**
   * FAQ field in *Faqs → Column Collapsible  → Primary → FAQs*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: faqs.columnCollapsible.primary.faqs[].faq
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  faq: prismic.ContentRelationshipField<'faq'>;
}

/**
 * Primary content in *Faqs → Default → Primary*
 */
export interface FaqsSliceDefaultPrimary {
  /**
   * Heading field in *Faqs → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faqs.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.RichTextField;

  /**
   * Subtitle field in *Faqs → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faqs.default.primary.subtitle
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  subtitle: prismic.KeyTextField;

  /**
   * Body field in *Faqs → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faqs.default.primary.body
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  body: prismic.RichTextField;

  /**
   * FAQs field in *Faqs → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: faqs.default.primary.faqs[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  faqs: prismic.GroupField<Simplify<FaqsSliceDefaultPrimaryFaqsItem>>;
}

/**
 * Default variation for Faqs Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FaqsSliceDefault = prismic.SharedSliceVariation<'default', Simplify<FaqsSliceDefaultPrimary>, never>;

/**
 * Primary content in *Faqs → Grid → Primary*
 */
export interface FaqsSliceGridPrimary {
  /**
   * Heading field in *Faqs → Grid → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faqs.grid.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.RichTextField;

  /**
   * Subtitle field in *Faqs → Grid → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faqs.grid.primary.subtitle
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  subtitle: prismic.KeyTextField;

  /**
   * Body field in *Faqs → Grid → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faqs.grid.primary.body
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  body: prismic.RichTextField;

  /**
   * FAQs field in *Faqs → Grid → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: faqs.grid.primary.faqs[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  faqs: prismic.GroupField<Simplify<FaqsSliceGridPrimaryFaqsItem>>;
}

/**
 * Grid variation for Faqs Slice
 *
 * - **API ID**: `grid`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FaqsSliceGrid = prismic.SharedSliceVariation<'grid', Simplify<FaqsSliceGridPrimary>, never>;

/**
 * Primary content in *Faqs → Column → Primary*
 */
export interface FaqsSliceColumnPrimary {
  /**
   * Heading field in *Faqs → Column → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faqs.column.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.RichTextField;

  /**
   * Subtitle field in *Faqs → Column → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faqs.column.primary.subtitle
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  subtitle: prismic.KeyTextField;

  /**
   * Body field in *Faqs → Column → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faqs.column.primary.body
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  body: prismic.RichTextField;

  /**
   * FAQs field in *Faqs → Column → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: faqs.column.primary.faqs[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  faqs: prismic.GroupField<Simplify<FaqsSliceColumnPrimaryFaqsItem>>;

  /**
   * Has Intro field in *Faqs → Column → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: faqs.column.primary.has_intro
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  has_intro: prismic.BooleanField;
}

/**
 * Column variation for Faqs Slice
 *
 * - **API ID**: `column`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FaqsSliceColumn = prismic.SharedSliceVariation<'column', Simplify<FaqsSliceColumnPrimary>, never>;

/**
 * Primary content in *Faqs → Column Collapsible  → Primary*
 */
export interface FaqsSliceColumnCollapsiblePrimary {
  /**
   * Heading field in *Faqs → Column Collapsible  → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faqs.columnCollapsible.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.RichTextField;

  /**
   * Subtitle field in *Faqs → Column Collapsible  → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faqs.columnCollapsible.primary.subtitle
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  subtitle: prismic.KeyTextField;

  /**
   * Body field in *Faqs → Column Collapsible  → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faqs.columnCollapsible.primary.body
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  body: prismic.RichTextField;

  /**
   * FAQs field in *Faqs → Column Collapsible  → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: faqs.columnCollapsible.primary.faqs[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  faqs: prismic.GroupField<Simplify<FaqsSliceColumnCollapsiblePrimaryFaqsItem>>;

  /**
   * Has Intro field in *Faqs → Column Collapsible  → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: faqs.columnCollapsible.primary.has_intro
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  has_intro: prismic.BooleanField;
}

/**
 * Column Collapsible  variation for Faqs Slice
 *
 * - **API ID**: `columnCollapsible`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FaqsSliceColumnCollapsible = prismic.SharedSliceVariation<
  'columnCollapsible',
  Simplify<FaqsSliceColumnCollapsiblePrimary>,
  never
>;

/**
 * Slice variation for *Faqs*
 */
type FaqsSliceVariation = FaqsSliceDefault | FaqsSliceGrid | FaqsSliceColumn | FaqsSliceColumnCollapsible;

/**
 * Faqs Shared Slice
 *
 * - **API ID**: `faqs`
 * - **Description**: Faqs
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FaqsSlice = prismic.SharedSlice<'faqs', FaqsSliceVariation>;

/**
 * Primary content in *HeaderBlock → Default → Primary*
 */
export interface HeaderBlockSliceDefaultPrimary {
  /**
   * Title field in *HeaderBlock → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: header_block.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Subtitle field in *HeaderBlock → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: header_block.default.primary.subtitle
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  subtitle: prismic.KeyTextField;
}

/**
 * Default variation for HeaderBlock Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeaderBlockSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<HeaderBlockSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *HeaderBlock*
 */
type HeaderBlockSliceVariation = HeaderBlockSliceDefault;

/**
 * HeaderBlock Shared Slice
 *
 * - **API ID**: `header_block`
 * - **Description**: HeaderBlock
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeaderBlockSlice = prismic.SharedSlice<'header_block', HeaderBlockSliceVariation>;

/**
 * Primary content in *Hero → Default → Primary*
 */
export interface HeroSliceDefaultPrimary {
  /**
   * Heading field in *Hero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading: prismic.KeyTextField;

  /**
   * Subheading field in *Hero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.subheading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  subheading: prismic.KeyTextField;

  /**
   * Links field in *Hero → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.links
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  links: prismic.Repeatable<prismic.LinkField>;

  /**
   * Image field in *Hero → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Default variation for Hero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSliceDefault = prismic.SharedSliceVariation<'default', Simplify<HeroSliceDefaultPrimary>, never>;

/**
 * Primary content in *Hero → Simple → Primary*
 */
export interface HeroSliceSimplePrimary {
  /**
   * Label field in *Hero → Simple → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.simple.primary.label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField;

  /**
   * Heading field in *Hero → Simple → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.simple.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading: prismic.KeyTextField;

  /**
   * Subheading field in *Hero → Simple → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.simple.primary.subheading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  subheading: prismic.KeyTextField;

  /**
   * Links field in *Hero → Simple → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.simple.primary.links
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  links: prismic.Repeatable<prismic.LinkField>;

  /**
   * Image field in *Hero → Simple → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.simple.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Simple variation for Hero Slice
 *
 * - **API ID**: `simple`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSliceSimple = prismic.SharedSliceVariation<'simple', Simplify<HeroSliceSimplePrimary>, never>;

/**
 * Slice variation for *Hero*
 */
type HeroSliceVariation = HeroSliceDefault | HeroSliceSimple;

/**
 * Hero Shared Slice
 *
 * - **API ID**: `hero`
 * - **Description**: Hero
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSlice = prismic.SharedSlice<'hero', HeroSliceVariation>;

/**
 * Item in *Section → Default → Primary → Images*
 */
export interface SectionSliceDefaultPrimaryImagesItem {
  /**
   * Image field in *Section → Default → Primary → Images*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: section.default.primary.images[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Item in *Section → Section numbers → Primary → Images*
 */
export interface SectionSliceSectionNumbersPrimaryImagesItem {
  /**
   * Image field in *Section → Section numbers → Primary → Images*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: section.sectionNumbers.primary.images[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Item in *Section → Section numbers → Primary → Numbers*
 */
export interface SectionSliceSectionNumbersPrimaryNumbersItem {
  /**
   * Heading field in *Section → Section numbers → Primary → Numbers*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: section.sectionNumbers.primary.numbers[].heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading: prismic.KeyTextField;

  /**
   * Decimals field in *Section → Section numbers → Primary → Numbers*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: section.sectionNumbers.primary.numbers[].decimals
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  decimals: prismic.NumberField;

  /**
   * Prefix field in *Section → Section numbers → Primary → Numbers*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: section.sectionNumbers.primary.numbers[].prefix
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  prefix: prismic.KeyTextField;

  /**
   * Suffix field in *Section → Section numbers → Primary → Numbers*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: section.sectionNumbers.primary.numbers[].suffix
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  suffix: prismic.KeyTextField;

  /**
   * Class Names field in *Section → Section numbers → Primary → Numbers*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: section.sectionNumbers.primary.numbers[].class_names
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  class_names: prismic.KeyTextField;

  /**
   * Start field in *Section → Section numbers → Primary → Numbers*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: section.sectionNumbers.primary.numbers[].start
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  start: prismic.NumberField;

  /**
   * End field in *Section → Section numbers → Primary → Numbers*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: section.sectionNumbers.primary.numbers[].end
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  end: prismic.NumberField;
}

/**
 * Item in *Section → Section List → Primary → List*
 */
export interface SectionSliceSectionListPrimaryListItem {
  /**
   * Icon field in *Section → Section List → Primary → List*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: section.sectionList.primary.list[].icon
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  icon: prismic.ImageField<never>;

  /**
   * Heading field in *Section → Section List → Primary → List*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: section.sectionList.primary.list[].heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading: prismic.KeyTextField;

  /**
   * Body field in *Section → Section List → Primary → List*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: section.sectionList.primary.list[].body
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  body: prismic.RichTextField;
}

/**
 * Primary content in *Section → Default → Primary*
 */
export interface SectionSliceDefaultPrimary {
  /**
   * Heading field in *Section → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: section.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading: prismic.KeyTextField;

  /**
   * Subheading field in *Section → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: section.default.primary.subheading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  subheading: prismic.KeyTextField;

  /**
   * Lead field in *Section → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: section.default.primary.lead
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  lead: prismic.KeyTextField;

  /**
   * Body field in *Section → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: section.default.primary.body
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  body: prismic.RichTextField;

  /**
   * Images field in *Section → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: section.default.primary.images[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  images: prismic.GroupField<Simplify<SectionSliceDefaultPrimaryImagesItem>>;
}

/**
 * Default variation for Section Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SectionSliceDefault = prismic.SharedSliceVariation<'default', Simplify<SectionSliceDefaultPrimary>, never>;

/**
 * Primary content in *Section → Section numbers → Primary*
 */
export interface SectionSliceSectionNumbersPrimary {
  /**
   * Heading field in *Section → Section numbers → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: section.sectionNumbers.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading: prismic.KeyTextField;

  /**
   * Body field in *Section → Section numbers → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: section.sectionNumbers.primary.body
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  body: prismic.RichTextField;

  /**
   * Images field in *Section → Section numbers → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: section.sectionNumbers.primary.images[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  images: prismic.GroupField<Simplify<SectionSliceSectionNumbersPrimaryImagesItem>>;

  /**
   * Numbers field in *Section → Section numbers → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: section.sectionNumbers.primary.numbers[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  numbers: prismic.GroupField<Simplify<SectionSliceSectionNumbersPrimaryNumbersItem>>;
}

/**
 * Section numbers variation for Section Slice
 *
 * - **API ID**: `sectionNumbers`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SectionSliceSectionNumbers = prismic.SharedSliceVariation<
  'sectionNumbers',
  Simplify<SectionSliceSectionNumbersPrimary>,
  never
>;

/**
 * Primary content in *Section → Section List → Primary*
 */
export interface SectionSliceSectionListPrimary {
  /**
   * Heading field in *Section → Section List → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: section.sectionList.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading: prismic.KeyTextField;

  /**
   * Subheading field in *Section → Section List → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: section.sectionList.primary.subheading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  subheading: prismic.KeyTextField;

  /**
   * Lead field in *Section → Section List → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: section.sectionList.primary.lead
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  lead: prismic.KeyTextField;

  /**
   * Body field in *Section → Section List → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: section.sectionList.primary.body
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  body: prismic.RichTextField;

  /**
   * List field in *Section → Section List → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: section.sectionList.primary.list[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  list: prismic.GroupField<Simplify<SectionSliceSectionListPrimaryListItem>>;

  /**
   * List Title field in *Section → Section List → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: section.sectionList.primary.list_title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  list_title: prismic.KeyTextField;
}

/**
 * Section List variation for Section Slice
 *
 * - **API ID**: `sectionList`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SectionSliceSectionList = prismic.SharedSliceVariation<
  'sectionList',
  Simplify<SectionSliceSectionListPrimary>,
  never
>;

/**
 * Slice variation for *Section*
 */
type SectionSliceVariation = SectionSliceDefault | SectionSliceSectionNumbers | SectionSliceSectionList;

/**
 * Section Shared Slice
 *
 * - **API ID**: `section`
 * - **Description**: Section
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SectionSlice = prismic.SharedSlice<'section', SectionSliceVariation>;

/**
 * Primary content in *Testimonial → Default → Primary*
 */
export interface TestimonialSliceDefaultPrimary {
  /**
   * Image field in *Testimonial → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonial.default.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Name field in *Testimonial → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonial.default.primary.name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField;

  /**
   * Position field in *Testimonial → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonial.default.primary.position
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  position: prismic.KeyTextField;

  /**
   * Body field in *Testimonial → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonial.default.primary.body
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  body: prismic.RichTextField;
}

/**
 * Default variation for Testimonial Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TestimonialSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<TestimonialSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Testimonial*
 */
type TestimonialSliceVariation = TestimonialSliceDefault;

/**
 * Testimonial Shared Slice
 *
 * - **API ID**: `testimonial`
 * - **Description**: Testimonial
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TestimonialSlice = prismic.SharedSlice<'testimonial', TestimonialSliceVariation>;

declare module '@prismicio/client' {
  interface CreateClient {
    (repositoryNameOrEndpoint: string, options?: prismic.ClientConfig): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (repositoryNameOrEndpoint: string, options: prismic.WriteClientConfig): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      AuthorDocument,
      AuthorDocumentData,
      ContactDocument,
      ContactDocumentData,
      ContactDocumentDataSlicesSlice,
      DownloadDocument,
      DownloadDocumentData,
      DownloadDocumentDataSlicesSlice,
      FaqDocument,
      FaqDocumentData,
      HomeDocument,
      HomeDocumentData,
      HomeDocumentDataSlicesSlice,
      LegalDocument,
      LegalDocumentData,
      LegalDocumentDataSlicesSlice,
      NavigationBarDocument,
      NavigationBarDocumentData,
      NavigationBarDocumentDataNavigationItemsItem,
      NavigationElementDocument,
      NavigationElementDocumentData,
      NavigationElementDocumentDataSubsItem,
      NavigationElementDocumentDataCtaItem,
      PageDocument,
      PageDocumentData,
      PageDocumentDataSlicesSlice,
      PostCategoryDocument,
      PostCategoryDocumentData,
      PostTagsDocument,
      PostTagsDocumentData,
      PostsDocument,
      PostsDocumentData,
      PostsDocumentDataTagsItem,
      PostsDocumentDataSlicesSlice,
      SettingsDocument,
      SettingsDocumentData,
      SettingsDocumentDataContactFormEnquiriesItem,
      SettingsDocumentDataSecondaryNavigationItem,
      SettingsDocumentDataSocialMediaItem,
      VideoDocument,
      VideoDocumentData,
      VideoDocumentDataSlicesSlice,
      AllDocumentTypes,
      CallToActionSlice,
      CallToActionSliceDefaultPrimary,
      CallToActionSliceImagePrimary,
      CallToActionSliceVariation,
      CallToActionSliceDefault,
      CallToActionSliceImage,
      FaqsSlice,
      FaqsSliceDefaultPrimaryFaqsItem,
      FaqsSliceDefaultPrimary,
      FaqsSliceGridPrimaryFaqsItem,
      FaqsSliceGridPrimary,
      FaqsSliceColumnPrimaryFaqsItem,
      FaqsSliceColumnPrimary,
      FaqsSliceColumnCollapsiblePrimaryFaqsItem,
      FaqsSliceColumnCollapsiblePrimary,
      FaqsSliceVariation,
      FaqsSliceDefault,
      FaqsSliceGrid,
      FaqsSliceColumn,
      FaqsSliceColumnCollapsible,
      HeaderBlockSlice,
      HeaderBlockSliceDefaultPrimary,
      HeaderBlockSliceVariation,
      HeaderBlockSliceDefault,
      HeroSlice,
      HeroSliceDefaultPrimary,
      HeroSliceSimplePrimary,
      HeroSliceVariation,
      HeroSliceDefault,
      HeroSliceSimple,
      SectionSlice,
      SectionSliceDefaultPrimaryImagesItem,
      SectionSliceDefaultPrimary,
      SectionSliceSectionNumbersPrimaryImagesItem,
      SectionSliceSectionNumbersPrimaryNumbersItem,
      SectionSliceSectionNumbersPrimary,
      SectionSliceSectionListPrimaryListItem,
      SectionSliceSectionListPrimary,
      SectionSliceVariation,
      SectionSliceDefault,
      SectionSliceSectionNumbers,
      SectionSliceSectionList,
      TestimonialSlice,
      TestimonialSliceDefaultPrimary,
      TestimonialSliceVariation,
      TestimonialSliceDefault,
    };
  }
}
