// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from 'next/dynamic';

export const components = {
  call_to_action: dynamic(() => import('./CallToAction')),
  faqs: dynamic(() => import('./Faqs')),
  header_block: dynamic(() => import('./HeaderBlock')),
  hero: dynamic(() => import('./Hero')),
  testimonial: dynamic(() => import('./Testimonial')),
};
